name: RDP avec ngrok

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest
    
    steps:
    - name: Activer RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
    - name: Créer utilisateur RDP
      run: |
        net user rdpuser "RDP123!" /add
        net localgroup administrators rdpuser /add
        
    - name: Télécharger et installer ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "."
        
    - name: Authentifier ngrok
      run: |
        ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Démarrer tunnel RDP
      run: |
        Start-Process -FilePath "./ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 10
        
    - name: Obtenir URL ngrok
      run: |
        $response = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels"
        $rdpUrl = $response.tunnels[0].public_url
        Write-Host "URL RDP: $rdpUrl"
        Write-Host "Utilisateur: rdpuser"
        Write-Host "Mot de passe: RDP123!"
        
    - name: Maintenir la connexion
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
          Write-Host "Connexion active..."
        }
